version: '3.8'

services:
  database-dev:
    image: postgres:15
    container_name: database-dev
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    
  postgres-test:
    image: postgres:15
    container_name: postgres_test
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  postgres_dev_data:
  postgres_test_data:

networks:
  postgres_network:
